#!/usr/bin/env python3
from pathlib import Path

N = 4096
LOG_N = 12
Q = 65537
COEFF_HEX_DIGITS = 5
G = 3
PSI = pow(G, (Q - 1) // (2 * N), Q)
OMEGA = pow(PSI, 2, Q)
INV_OMEGA = pow(OMEGA, -1, Q)
INV_N = pow(N, -1, Q)
INV_PSI = pow(PSI, -1, Q)

ROOT = Path(__file__).resolve().parents[1]
TABLE = ROOT / "table"
TB = ROOT / "tb"
TABLE.mkdir(exist_ok=True)
TB.mkdir(exist_ok=True)


def write_mem(path: Path, values):
    with path.open("w") as f:
        for v in values:
            f.write(f"{v % Q:0{COEFF_HEX_DIGITS}x}\n")


def make_forward_twiddles():
    vals = []
    m = N
    while m >= 2:
        half = m // 2
        step = N // m
        for j in range(half):
            vals.append(pow(OMEGA, j * step, Q))
        m //= 2
    vals.append(0)  # pad to DEPTH=N
    assert len(vals) == N
    return vals


def make_inverse_twiddles():
    vals = []
    m = 2
    while m <= N:
        half = m // 2
        step = N // m
        for j in range(half):
            vals.append(pow(INV_OMEGA, j * step, Q))
        m *= 2
    vals.append(0)  # pad to DEPTH=N
    assert len(vals) == N
    return vals


def make_vectors():
    # Deterministic, non-file-based test vectors.  The testbench includes these
    # as hardwired assignments so a/b can be edited directly in tb/hardwired_vectors.svh.
    a = [((5 * i * i + 17 * i + 123) % Q) for i in range(N)]
    b = [((7 * i * i + 29 * i + 456) % Q) for i in range(N)]
    return a, b


def direct_negacyclic_mul(a, b):
    c = [0] * N
    for i, ai in enumerate(a):
        for j, bj in enumerate(b):
            p = (ai * bj) % Q
            k = i + j
            if k >= N:
                c[k - N] -= p
            else:
                c[k] += p
        if (i & 127) == 0:
            c = [x % Q for x in c]
    return [x % Q for x in c]


def write_hardwired_vectors(path: Path, a, b):
    add = [(x + y) % Q for x, y in zip(a, b)]
    mul = direct_negacyclic_mul(a, b)
    with path.open("w") as f:
        f.write("// Auto-generated by scripts/gen_tables.py.\n")

        for name, vec in [("a_init", a), ("b_init", b), ("exp_add", add), ("exp_mul", mul)]:
            f.write(f"// {name}\n")
            for i, v in enumerate(vec):
                f.write(f"{name}[{i}] = {17}'d{v};\n")
            f.write("\n")


def main():
    assert pow(PSI, N, Q) == Q - 1
    assert pow(PSI, 2 * N, Q) == 1
    assert pow(OMEGA, N, Q) == 1

    write_mem(TABLE / "twiddle_fwd.mem", make_forward_twiddles())
    write_mem(TABLE / "twiddle_inv.mem", make_inverse_twiddles())
    write_mem(TABLE / "twist_fwd.mem", [pow(PSI, i, Q) for i in range(N)])
    write_mem(TABLE / "twist_inv_scale.mem", [(INV_N * pow(INV_PSI, i, Q)) % Q for i in range(N)])

    a, b = make_vectors()
    write_hardwired_vectors(TB / "hardwired_vectors.svh", a, b)

    print(f"N={N}")
    print(f"Q={Q}")
    print(f"PSI={PSI}")
    print(f"OMEGA={OMEGA}")
    print(f"INV_OMEGA={INV_OMEGA}")
    print(f"INV_N={INV_N}")
    print("Generated table/*.mem and tb/hardwired_vectors.svh")


if __name__ == "__main__":
    main()
